---

- name: restart varnish
  become: yes
  service:
    name: varnish
    state: restarted
  register: restart_varnish_handler
    
- name: reload varnish
  when: "{{ restart_varnish_handler is not defined }}"
  become: yes
  service:
    name: varnish
    state: reloaded

- name: restart daemon tools
  # BBB (1-Feb-2016) ubuntu 14.04
  when: ansible_distribution_release != "trusty"
  become: yes
  # This makes our service file changes available for use.
  shell: systemctl daemon-reload
