---
root_prefix: ""

archive_db_name: "{{ vault_archive_db_name }}"
archive_db_user: "{{ vault_archive_db_user }}"
archive_db_password: "{{ vault_archive_db_password }}"
archive_db_host: prod09.cnx.org
archive_db_port: 5432

publishing_broker_user: "{{ vault_publishing_broker_user }}"
publishing_broker_password: "{{ vault_publishing_broker_password }}"

press_db_name: "{{ archive_db_name }}"
press_db_user: "{{ archive_db_user }}"
press_db_password: "{{ archive_db_password }}"
press_db_host: "{{ archive_db_host }}"
press_db_port: "{{ archive_db_port }}"
press_broker_user: "{{ vault_press_broker_user }}"
press_broker_password: "{{ vault_press_broker_password }}"

sentry_dsn: "{{ vault_sentry_dsn }}"

s3_access_key: "{{ vault_s3_access_key }}"
s3_secret_key: "{{ vault_s3_secret_key }}"
s3_encryption_pw: "{{ vault_s3_encryption_pw }}"

install_iptables: true

memcached_hosts: localhost

varnish_port: 80
legacy_varnish_port: 8991

archive_base_port: "{{ default_archive_base_port }}"
publishing_base_port: "{{ default_publishing_base_port }}"
zclient_base_port: "{{ default_zclient_base_port }}"
authoring_host: beta.cnx.org

zope_domain: legacy.cnx.org
arclishing_domain: archive.cnx.org
frontend_domain: cnx.org
accounts_domain: accounts-stage1.openstax.org
tutor_domain: tutor.openstax.org
exercises_domain: exercises.openstax.org
cms_domain: openstax.org

# See group_vars/all.yml for defaults
graylog_port: 5141
graylog_server: "{{ default_graylog_server }}"

accounts_disable_verify_ssl: yes
accounts_stub: yes

accounts_consumer_token: "{{ vault_accounts_consumer_token }}"
accounts_consumer_secret: "{{ vault_accounts_consumer_secret }}"

exercises_token: "{{ vault_exercises_token }}"

postgres_connections: "{{ vault_postgres_connections }}"

slack_token: "{{ vault_slack_token }}"

archive_exports_directories:
  - files3
  - files
  - files2
  - files4

nfs_mounts:
  - name: /var/www/files
    src: /var/www/files
    server: prod-files00.cnx.org
  - name: /var/www/files2
    src: /var/www/files2
    server: prod-files00.cnx.org
  - name: /var/www/files3
    src: /var/www/files3
    server: prod-files01.cnx.org
  - name: /var/www/files4
    src: /var/www/files4
    server: prod-files01.cnx.org
  - name: /var/www/specials
    src: /var/www/specials
    server: prod-files00.cnx.org
  - name: /var/www/varnish_logs
    src: /var/www/varnish_logs
    server: prod-files00.cnx.org

nfs_connections: "{{ vault_nfs_connections }}"

google_site_verification_filename: "{{ vault_google_site_verification_filename }}"

blocked_ip_addresses: "{{ vault_blocked_ip_addresses }}"

princexml_deb_url: "http://www.princexml.com/download/prince_11-1_ubuntu16.04_amd64.deb"
