---
root_prefix: ""

archive_db_name: "{{ vault_archive_db_name }}"
archive_db_user: "{{ vault_archive_db_user }}"
archive_db_password: "{{ vault_archive_db_password }}"
archive_db_host: prod09.cnx.org
archive_db_port: 5432

memcached_hosts: localhost

varnish_port: 80

archive_base_port: "{{ default_archive_base_port }}"
publishing_base_port: "{{ default_publishing_base_port }}"
zclient_base_port: "{{ default_zclient_base_port }}"
authoring_host: beta.cnx.org

zope_domain: legacy.cnx.org
arclishing_domain: archive.cnx.org
frontend_domain: cnx.org
accounts_domain: accounts.openstax.org
tutor_domain: tutor.openstax.org
exercises_domain: exercises.openstax.org

# See group_vars/all.yml for defaults
graylog_port: 5141
graylog_server: "{{ default_graylog_server }}"

accounts_consumer_token: "{{ vault_accounts_consumer_token }}"
accounts_consumer_secret: "{{ vault_accounts_consumer_secret }}"
accounts_disable_verify_ssl: no

exercises_token: "{{ vault_exercises_token }}"

postgres_connections: "{{ vault_postgres_connections }}"

slack_token: "{{ vault_slack_token }}"

nfs_server_for_files1: prod-files00.cnx.org
nfs_server_for_files2: prod-files00.cnx.org
nfs_server_for_specials: prod-files00.cnx.org
nfs_server_for_varnish_logs: prod-files00.cnx.org

nfs_connections: "{{ vault_nfs_connections }}"

webview_version: v0.22.2

google_site_verification_filename: "{{ vault_google_site_verification_filename }}"

blocked_ip_addresses: "{{ vault_blocked_ip_addresses }}"

concept_coach_webview_settings:
  '08df2bee-3db4-4243-bd76-ee032da173e8': ['self-check-questions','review-questions','critical-thinking','problems']
  'CN8r7j20': ['self-check-questions','review-questions','critical-thinking','problems']
  '27275f49-f212-4506-b3b1-a4d5e3598b99': ['conceptual-questions','problems-exercises']
  'JydfSfIS': ['conceptual-questions','problems-exercises']
  '4f86c023-a135-412a-9d96-dcbd1ca61e7d': ['section-quiz','short-answer','further-research']
  'T4bAI6E1': ['section-quiz','short-answer','further-research']
  'd393e255-30b3-4ba7-bc78-2fd7a4324ec8': ['section-quiz','short-answer','further-research']
  '05PiVTCz': ['section-quiz','short-answer','further-research']
  '947a1417-5fd5-4b3c-ac8f-bd9d1aedf2d2': ['self-check-questions','review-questions','critical-thinking','problems']
  'lHoUF1_V': ['self-check-questions','review-questions','critical-thinking','problems']
  'bf96bfc5-e723-46c2-9fa2-5a4c9294fa26': ['art-exercise','multiple-choice','free-response']
  'v5a_xecj': ['art-exercise','multiple-choice','free-response']
  'd2fbadca-e4f3-4432-a074-2438c216b62a': ['self-check-questions','review-questions','critical-thinking','problems']
  '0vutyuTz': ['self-check-questions','review-questions','critical-thinking','problems']
  '3402dc53-113d-45f3-954e-8d2ad1e73659': ['art-exercise','multiple-choice','free-response']
  'NALcUxE9': ['art-exercise','multiple-choice','free-response']
  '99e127f8-f722-4907-a6b3-2d62fca135d6': ['art-exercise','multiple-choice','free-response','interactive-exercise']
  'meEn-Pci': ['art-exercise','multiple-choice','free-response']

princexml_deb_url: "http://www.princexml.com/download/prince_11-1_ubuntu16.04_amd64.deb"
