---

- name: iptables chain setup
  become: yes
  copy:
    src: etc/network/if-up.d/iptables
    dest: /etc/network/if-up.d/iptables
    mode: 0744

- name: iptables template setup
  become: yes
  template:
    src: etc/iptables
    dest: /etc/iptables.up.rules
    mode: 0644
  tags:
    - iptables-template

- name: iptables restore of template
  become: yes
  command: iptables-restore /etc/iptables.up.rules

- name: rsyslog iptables template
  template:
    src: etc/rsyslog.d/40-iptables.conf
    dest: /etc/rsyslog.d/40-iptables.conf
    mode: 0644
  notify:
    - restart rsyslog
  tags:
    - iptables-rsyslog
