---

- name: lookup extensions location
  command: "pg_config --pkglibdir"
  register: _pg_pkglibdir

- name: check for session_exec.so
  stat:
    path: "{{ _pg_pkglibdir.stdout }}/session_exec.so"
  register: session_exec_so

- import_tasks: install_session_exec.yml
  when: not session_exec_so.stat.exists

- import_tasks: plpython_imports.yml
