---
# Configure HAProxy

- name: configure haproxy zcluster
  become: yes
  blockinfile:
    dest: /etc/haproxy/haproxy.cfg
    state: present
    marker: "# {mark} zcluster block ANSIBLE MANAGED BLOCK"
    insertafter: EOF
    block: |
      {% if single_instance is undefined %}
      frontend zcluster
        bind :8888
        default_backend zclients
      {% endif %}
      # Load balancing over the zope instances
      backend zclients
        # Use Zope's __ac cookie as a basis for session stickiness if present.
        # appsession __ac len 32 timeout 1d
        # Otherwise add a cookie called "serverid" for maintaining session stickiness.
        # This cookie lasts until the client's browser closes, and is invisible to Zope.
        #  cookie serverid insert nocache indirect
        # If no session found, use the roundrobin load-balancing algorithm to pick a backend.
        balance leastconn
        # Use / (the default) for periodic backend health checks
        option httpchk

        # Server options:
        # "cookie" sets the value of the serverid cookie to be used for the server
        # "maxconn" is how many connections can be sent to the server at once
        # "check" enables health checks
        # "rise 1" means consider Zope up after 1 successful health check
      {% for host in groups.zclient %}
      {% set ip_addr = hostvars[host].ansible_default_ipv4.address %}
      {% for i in range(0, hostvars[host].zclient_count|default(1), 1) %}
        server {{ host }}{{ i }} {{ ip_addr }}:{{ zclient_base_port + i }} check maxconn 4 rise 1
      {% endfor %}
      {% endfor %}

      {# FIXME (10-Oct-2016) phased-deploy #}
      {#       This has been added to allow for the front-end to be deployed without configuring the backend bits of the system. Please remove on next phase of deployment. #}
      {% for item in xxx_hardcoded_zclients|default([]) %}
      {% set ip_addr = item.ip_addr %}
      {% set host = item.host %}
      {# Note, legacy zope client ports increment by one hundred #}
      {% for i in range(0, item.count+1, 1) %}
        server {{ host }}{{ i }} {{ ip_addr }}:8{{ '{0:0>3}'.format(100*i+80) }} check maxconn 4 rise 1
      {% endfor %}
      {% endfor %}
      {# /FIXME phased-deploy #}
    owner: root
    group: root
    mode: 0644
  notify:
    - reload haproxy
  tags:
    - haproxy
