---
# Configure HAProxy

- name: gather facts from zope and frontend servers
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: yes
  with_items:
    - "{{ groups.zope }}"
    - "{{ groups.lead_frontend }}"
    - "{{ groups.frontend }}"

- name: configure lead load balancer
  become: yes
  blockinfile:
    dest: /etc/haproxy/haproxy.cfg
    state: present
    marker: "# {mark} lead block ANSIBLE MANAGED BLOCK"
    insertafter: EOF
    block: |
      frontend http-proxy
        bind *:80
        bind *:443 ssl crt /etc/ssl/certs/{{ frontend_domain }}.pem

        http-response set-header Strict-Transport-Security "max-age=16000000"
        http-request set-header X-Secure true if { ssl_fc }
        http-request set-header X-Forwarded-Proto https if { ssl_fc }

        acl is_legacy hdr(host) -i {{ zope_domain }}
        acl is_arclishing hdr(host) -i {{ arclishing_domain }}
        acl is_cnxorg hdr(host) -i {{ frontend_domain }}
        acl has_www hdr_beg(host) -i www
        acl from_zope src 127.0.0.1 {% for host in groups.zope %}{{ hostvars[host].ansible_default_ipv4.address }} {% endfor %}

        http-request redirect scheme https code 301 if ! from_zope ! { ssl_fc }
        http-request redirect prefix http://{{ frontend_domain }}%[req.uri] code 301 if has_www ! { ssl_fc }
        http-request redirect prefix https://{{ frontend_domain }}%[req.uri] code 301 if has_www { ssl_fc }

        use_backend legacy_nodes if is_legacy
        use_backend nodes if is_cnxorg
        use_backend nodes if is_arclishing
        default_backend nodes

      # Load balancing the frontend grouping
      backend nodes
        balance uri
        option httpchk GET /ping HTTP/1.1\r\nHOST:\ {{ frontend_domain }}
        option forwardfor

        # Server options:
        # "check" enables health checks
        # "rise 1" means consider the frontend up after 1 successful health check
      {% for host in groups.frontend %}
      {% set ip_addr = hostvars[host].ansible_default_ipv4.address %}
        server {{ host }} {{ ip_addr }}:{{ varnish_port }} check inter 30s rise 1
      {% endfor %}

      # Load balancing the frontend grouping
      backend legacy_nodes
        balance roundrobin
        option httpchk OPTIONS * HTTP/1.1\r\nHOST:\ {{ zope_domain }}
        option forwardfor

        # Server options:
        # "check" enables health checks
        # "rise 1" means consider the frontend up after 1 successful health check
      {% for host in groups.legacy_frontend %}
      {% set ip_addr = hostvars[host].ansible_default_ipv4.address %}
        server {{ host }} {{ ip_addr }}:{{ varnish_port }} check inter 30s rise 1
      {% endfor %}
    owner: root
    group: root
    mode: 0644
  notify:
    - reload haproxy
