---
root_prefix: ""

archive_db_name: "{{ vault_archive_db_name }}"
archive_db_user: "{{ vault_archive_db_user }}"
archive_db_password: "{{ vault_archive_db_password }}"
archive_db_host: staging00.cnx.org
archive_db_port: 5432

# FIXME Not really yaml'ish to use space separated values...
# Note, don't confuse the usage of 'hosts' here with ansible 'hosts'.
# 'hosts' is a space separated value containing hostnames or ip addresses
# where a memcached instance is running.
memcached_hosts: localhost

varnish_port: 80

archive_host: tundra.cnx.rice.edu
archive_port: 8888
publishing_host: tundra.cnx.rice.edu
publishing_port: 6550
authoring_host: staging00.cnx.org
authoring_port: 6420

zope_domain: legacy-staging00.cnx.org
arclishing_domain: archive-staging00.cnx.org
frontend_domain: staging00.cnx.org
accounts_domain: accounts.openstax.org
tutor_domain: tutor.openstax.org
exercises_domain: exercises.openstax.org

accounts_consumer_token: "{{ vault_accounts_consumer_token }}"
accounts_consumer_secret: "{{ vault_accounts_consumer_secret }}"
accounts_disable_verify_ssl: no

postgres_connections: "{{ vault_postgres_connections }}"

slack_token: "{{ vault_slack_token }}"

nfs_server_for_files1: staging-files00.cnx.org
nfs_server_for_files2: staging-files00.cnx.org

webview_version: v0.21.0

xxx_hardcoded_zclients:
  - ip_addr: 128.42.169.13
    host: glad
    count: 2
  - ip_addr: 128.42.169.17
    host: quil
    count: 5
  - ip_addr: 128.42.169.18
    host: font
    count: 5

blocked_ip_addresses: "{{ vault_blocked_ip_addresses }}"

concept_coach_webview_settings:
  '08df2bee-3db4-4243-bd76-ee032da173e8': ['self-check-questions','review-questions','critical-thinking','problems']
  'CN8r7j20': ['self-check-questions','review-questions','critical-thinking','problems']
  '27275f49-f212-4506-b3b1-a4d5e3598b99': ['conceptual-questions','problems-exercises']
  'JydfSfIS': ['conceptual-questions','problems-exercises']
  '4f86c023-a135-412a-9d96-dcbd1ca61e7d': ['section-quiz','short-answer','further-research']
  'T4bAI6E1': ['section-quiz','short-answer','further-research']
  'd393e255-30b3-4ba7-bc78-2fd7a4324ec8': ['section-quiz','short-answer','further-research']
  '05PiVTCz': ['section-quiz','short-answer','further-research']
  '947a1417-5fd5-4b3c-ac8f-bd9d1aedf2d2': ['self-check-questions','review-questions','critical-thinking','problems']
  'lHoUF1_V': ['self-check-questions','review-questions','critical-thinking','problems']
  'bf96bfc5-e723-46c2-9fa2-5a4c9294fa26': ['art-exercise','multiple-choice','free-response']
  'v5a_xecj': ['art-exercise','multiple-choice','free-response']
  'd2fbadca-e4f3-4432-a074-2438c216b62a': ['self-check-questions','review-questions','critical-thinking','problems']
  '0vutyuTz': ['self-check-questions','review-questions','critical-thinking','problems']
  '3402dc53-113d-45f3-954e-8d2ad1e73659': ['art-exercise','multiple-choice','free-response']
  'NALcUxE9': ['art-exercise','multiple-choice','free-response']
  '99e127f8-f722-4907-a6b3-2d62fca135d6': ['art-exercise','multiple-choice','free-response','interactive-exercise']
  'meEn-Pci': ['art-exercise','multiple-choice','free-response']
