---
root_prefix: ""

archive_db_name: "{{ vault_archive_db_name }}"
archive_db_user: "{{ vault_archive_db_user }}"
archive_db_password: "{{ vault_archive_db_password }}"
archive_db_host: tea00.cnx.org
archive_db_port: 5432

publishing_broker_user: "{{ vault_publishing_broker_user }}"
publishing_broker_password: "{{ vault_publishing_broker_password }}"

# authoring_db_name: "{{ vault_authoring_db_name }}"
# authoring_db_user: "{{ vault_authoring_db_user }}"
# authoring_db_password: "{{ vault_authoring_db_password }}"
# authoring_db_host: tea00.cnx.org
# authoring_db_port: 5432

# FIXME Not really yaml'ish to use space separated values...
# Note, don't confuse the usage of 'hosts' here with ansible 'hosts'.
# 'hosts' is a space separated value containing hostnames or ip addresses
# where a memcached instance is running.
memcached_hosts: localhost

varnish_port: 8990

archive_host: tea00.cnx.org
publishing_host: tea00.cnx.org
authoring_host: tea00.cnx.org
zclient_base_port: 8280

zope_domain: legacy-tea.cnx.org
arclishing_domain: archive-tea.cnx.org
frontend_domain: tea.cnx.org
accounts_domain: accounts-qa1.openstax.org
tutor_domain: openstaxtutor.org
exercises_domain: exercises.openstax.org

accounts_disable_verify_ssl: yes
accounts_stub: yes

accounts_consumer_token: "{{ vault_accounts_consumer_token }}"
accounts_consumer_secret: "{{ vault_accounts_consumer_secret }}"

exercises_token: "{{ vault_exercises_token }}"

postgres_connections: "{{ vault_postgres_connections }}"

slack_token: "{{ vault_slack_token }}"

nfs_server_for_files1: tea00.cnx.org
nfs_server_for_files2: tea00.cnx.org
nfs_server_for_specials: tea00.cnx.org
nfs_server_for_varnish_logs: tea00.cnx.org

webview_version: master

princexml_deb_url: "http://www.princexml.com/download/prince_11-1_ubuntu16.04_amd64.deb"
